apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: tckt
build:
  artifacts:
    - image: tcktacrn.azurecr.io/auth
      context: auth
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - infra/k8s/auth.depl.yaml
    - infra/k8s/ingress-srv.yaml
