apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: tcktacrn.azurecr.io/expiration:latest  # Replace tcktcontainerregistry with your actual ACR name
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: tckt
            - name: REDIS_HOST
              value: expiration-redis-srv
      
      imagePullSecrets:
        - name: tckt
